<form action="" method="POST">
  <label>Username:</label>
  <input type="text" name="username"><br>

  <label>Email:</label>
  <input type="text" name="email"><br>
  
  <label>Usia (integer):</label>
  <input type="text" name="usia"><br>

  <label>Tahun (integer):</label>
  <input type="text" name="tahun"><br>

  <label>Homepage (URL):</label>
  <input type="text" name="url"><br>

  <label>IP Address:</label>
  <input type="text" name="ip_address"><br>

  <label>Tanggal Lahir (YYYY-MM-DD):</label>
  <input type="text" name="tanggal_lahir"><br>
  <div class="field">
    <button type="submit">Submit</button>
  </div>
</form>